### ISSUE TITLE
Ad. Mech QA

### ISSUE THREAD

**Issue by KevinFournier** [RosterizerTestData/Warhammer40k10e#112]
## Cawl Ability description

See this other issue: https://github.com/RosterizerTestData/Warhammer40k10e/issues/99#issue-1787084015

## Pteraxii Skystalkers

The last part of the `Ride the thermal` ability description is merged with the bullet point sentence. (see below)
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/11573588/32a5a470-8f17-4dcb-b1ad-916d6a9bd83a)

The sentence `In either case, if it does, until the end of the turn, this unit is not eligible to declare a charge.` should be it’s own paragraph.

### Default loadout

The default loadout on non-alpha sulphurhounds should be their Twin phosphor pistols. 
Because:
- This is the normal default loadout
- Having a blast carabine on all sulphurhounds is not possible, so an error is displayed when creating the unit

### Sulphurhound Alpha weapon keyword.

Alpha’s Cavalry arc maul is missing all it’s keywords: `anti-vehicle 4+`, `devastating wounds` and `extra attacks`. (as in image below)
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/11573588/55cebaee-95c6-4943-89ca-33f0f4316123)

## Servitors

Their default loadout should be `servo-arms` alones. Because:
- It’s their default loadout
- It is not possible to have more than two weapon options on servitors so an error is displayed when creating the unit.
- Yes, _Ad. Mech._ servitors  datasheet is the worst serivtors datasheets of the imperium.

### Optional Phosphor Serpenta:

The option checkbox exists but is not interactable. Missing the `dynamic: "true` atribut l. 3734 ?
(Checkbox in the image below)
 
 ### Missing melee weapon:

Ironstrider feets is described in the register but is not display in the UI when selecting the loadout `Radium Jezzail and Ironstrider feet.
(In the image below, only the Jezzail is displayed)

![Screenshot from 2023-07-08 19-09-39](https://github.com/RosterizerTestData/Warhammer40k10e/assets/11573588/68ae8948-91ad-4b2b-b768-8feca86f98c4)

**Comment by Nemo3823** [comment]
Should all be fixed in 10.2.9, thanks!
