### ISSUE TITLE
Sisters QA issues

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#120]
- [x] Spirit of the Martyr stratagem missing text
- [x] Morvenn Vahl is allowed to not be the warlord
- [x] Blade of Saint Ellynor enhancement is not adding A/S/D to melee weapons
- [x] Mantle of Ophelia enhancement not restricted to Canoness/Palatine
- [x] Acts of Faith ability (and likely others) has block bullets and no line breaks. (Text in Rosterizer is rendered as Markdown, so instead of leaving in the ■ symbol that bullet points get imported as, put each one on a new line and start it with `-` and you get actual bullets.)
- [x] Missionary has wrong default loadout, should be holy pistol and power weapon.
- [x] Celestine has all keywords on the unit; some should only be on Celestine's model.
- [x] Celestine model is named "Celestine - Epic Hero", should just be "Celestine"
- [x] Triumph of Saint Katherine - Relic Weapons missing weaponName stat
- [x] Triumph of Saint Katherine - Relics of the Matriarchs ability name has a colon in it
- [x] Triumph of Saint Katherine - Damaged ability is incorrect (you need to put the text in the `x` stat rather than attempting to override the ability's text)
- [x] Triumph of Saint Katherine - Leader ability is incorrect
- [x] Daemonifuge - model names contain "Epic Hero`
- [x] Daemonifuge - Kyganil has the same characteristics as Ephrael
- [x] Battle Sisters Squad - "Maximum 1 Special Weapon if there is 1 Heavy Weapon" rule is triggered with no special weapons in the squad. (Not sure under _exactly_ what circumstances, but I spotted it when I gave everyone a heavy weapon.)
- [x] Battle Sisters Squad - "Maximum 1 Special Weapon if there is 1 Heavy Weapon" rule is triggered with 3 special weapons and no heavy weapons in the squad.
- [x] Battle Sisters Squad - Sister Superior shouldn't be required to take a melee weapon
- [x] Sisters Novitiate Squad - Sisters Novitiate have the same characteristics as the Novitiate Superior
- [x] Aestred Thurga and Agathae Dolan - ability links are broken, probably a capitalisation issue
- [x] Aestred Thurga and Agathae Dolan - model names contain Epic Hero
- [x] Aestred Thurga and Agathae Dolan - Agathae has the same characteristics as Aestred
- [x] Imagifier - last line of Leader ability has merged into the fourth bullet
- [x] Dialogus - last line of Leader ability has merged into the fifth bullet
- [x] Preacher - wargear incorrectly defaulted to autopistol/chainsword
- [x] Hospitaller - last line of Leader ability has merged into the fifth bullet
- [x] Dogmata - last line of Leader ability has merged into the fourth bullet
- [x] Dominion Squad - unit has the Simulacrum wargear at unit scope
- [x] Dominion Squad - Superior defaults to double bolt pistol instead of boltgun
- [x] Seraphim Squad - "Maximum 2 Special Pistols" rule still triggering with 10 models
- [x] Zephyrim Squad - Superior is defaulting to having the banner (feel free to reject this if you're going for a principle of diverging from the datasheets to make people's lives easier!)
- [x] Mortifiers - Anchorite Sarcophagus is not modifying bearer's Save characteristic
- [x] Mortifiers - incorrect default melee weapon option
- [x] Penitent Enginers - incorrect default weapon option
- [x] Exorcist - incorrect default weapon option
- [x] Exorcist - hunter-killer missile One Shot ability has no text
- [x] Castigator - hunter-killer missile One Shot ability has no text
- [x] Sororitas Rhino - hunter-killer missile One Shot ability has no text
- [x] Immolator - hunter-killer missile One Shot ability has no text

**Comment by Nemo3823** [comment]
Fixed in 10.3.0
