### ISSUE TITLE
TSons QA issues

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#121]
- [x] Cabal of Sorcerers: ability is empty (Also no way to see rituals, maybe making another category right below the stratagems and detachment ability?)
- [x] Arcane Vortex: Enhancement doesn't add stats
- [x] Athenaean Scrolls: Considering you added a Cabal tracker, would it be worth it to also make this count as 1 CP?)
- [x] Ahriman: Currently Ahriman on Disc removes Ahriman from the pool but Ahriman doesn't remove Ahriman on disc from the pool (Would it be better to not remove them and just give a warning? Users might not realize they need to delete one Ahriman to find the other)
- [x] Thousand Sons Rhino: Error in text
- [x] Defiler: Scuttling Walker repeats text
- [x] Defiler: Can't be equipped with an Inferno combi-weapon
- [x] Exalted Sorcerer on Disc of Tzeentch: Error in text
- [x] Thousand Sons Forgefiend: Jaws/Claws loadout doesn't give an ectoplasma cannon
- [x] Rubric Marines: Have "ALL Models:" and "Aspiring Sorcerer:" Keywords
- [x] Rubric Marines: Cabal of Sorcerers 1 should go on the Aspiring Sorcerer
- [x] Scarab Occult Terminators: Have "ALL Models:" and "Aspiring Sorcerer:" Keywords
- [x] Scarab Occult Terminators: Cabal of Sorcerers 1 should go on the Aspiring Sorcerer
- [x] Tzaangor Enlightened: Enlightened have "sampleLoadout"

**Comment by Nemo3823** [comment]
Fixed in 10.3.0
