### ISSUE TITLE
Nids: Warriors with ranged weapons allowed extra heavy weapon if it's on the Prime

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#122]
Ranged Warriors are allowed 1 heavy weapon per 3 models. However, the Prime seems to bypass this limit and is allowed to take a heavy weapon that would cause the unit overall to have too many heavy weapons.

**Comment by TheGameKnave** [comment]
The heavy weapons are keyed; the unit can have 1 in 3 of each of the two.
<img width="174" alt="image" src="https://github.com/RosterizerTestData/Warhammer40k10e/assets/575686/4e1e16dd-01ec-4fe4-81e5-edeef4517fb6">
<img width="199" alt="image" src="https://github.com/RosterizerTestData/Warhammer40k10e/assets/575686/7ee9e5e4-1751-4389-8008-bd1b85a15917">
<img width="376" alt="image" src="https://github.com/RosterizerTestData/Warhammer40k10e/assets/575686/c089298d-38ff-43c8-99ad-d3d404331b1c">

**Comment by ThePants999** [comment]
Yes, but you can take 2 venom cannons in a 3-model unit because of this bug.

**Comment by TheGameKnave** [comment]
Fixed in 10.3.2 (venomCanon)
