### ISSUE TITLE
Eldar QA issues

### ISSUE THREAD

**Issue by Nemo3823** [RosterizerTestData/Warhammer40k10e#124]
- [x] Howling Banshee Mask: 
    Should give Fights First Ability

- [x] Corsair Voidreavers:
    Shuriken canno, Wraithcannon, and are not listed as a loadout when Shuriken Rifle is selected
    Corsair blaster and Corsair Shredder are not listed as a loadout when Shuriken Pistol is selected
    Shuriken Pistol/Aeldari power sword and Corsair pistol + Shuriken pistol/Aeldari power sword and Corsair Shredder are illegal loadouts
    Should not have to select Shuriken rifle on the wargear to see heavy weapons on a different tab
    It is not possible to split unit between Shuriken pisto/Aeldari power sword and Shuriken Rifle

- [x] Corsair Voidscarred:
    Shuriken cannon, Wraithcannon, and Ranger long rifle are not listed as a loadout when Shuriken Rifle is selected
    Corsair blaster and Corsair shredder are not listed as a loadout when Shuriken Pistol is selected
    Shuriken Pistol/Aeldari power sword and Corsair pistol + Shuriken pistol/Aeldari power sword and Corsair Shredder are illegal loadouts
    Giving a model a Faolchú takes away theyir Shuriken pistol and Aeldari power sword
    Should not have to select Shuriken rifle on the wargear to see heavy weapons on a different tab
    It is not possible to split unit between Shuriken pisto/Aeldari power sword and Shuriken Rifle

- [x] Crimson Hunter:
    Pulse laser and Wraithbone hull are Included assets instead of Trait assets - Gives error message

- [x] Dire Avengers:
    Dire Avengers loadout name is sampleLoadout

- [x] Falcon:
    Pulse laser and Wraithbone hull are Included assets instead of Trait assets - Gives error message

- [x] Fire Prism:
    Prism Cannon and Wraithbone hull are Included assets instead of Trait assets - Gives error message

- [x] Guardian Defenders:
    Crewed platform ability repeats itself

- [x] Swooping Hawks:
    Swooping Hawks have to take lasblasters and shouldn't have a loadout option
    Swooping Hawks missing close combat weapon
- [x] Windriders:
    Windrider model is plural

- [x] Wraithblades:
    Wraithblade model is plural

- [x] Wraithknight:
    Missing Titanic feet

- [x] Wraithlord:
    Not necessary, but should probably order loadouts so that they go from 1st - 4th (Currently 1-4-2-3)

- [x] Wraithseer:
    Ghostspear and Missile launcher have Wraithseer in name

- [x] Phantom Titan:
    Wraith Glaive has Phantom Titan in name

- [x] Cobra:
    Missile launcher has Cobra in name

- [x] Scorpion:
    Missile launcher has Scorpion in name

- [x] Warp Hunter:
    D-flail has Warp hunter in name

- [x] Lynx:
    Missile launcher has Lynx in name

- [x] Hornet:
    Missile launcher has Hornet in name

- [x] Shadow Spectres:
    Prism rifle has Shadow Spectres in name
    Shadow Spectre Exarch has a 5+ save listed instead of 3+

- [x] Skathach Wraithknight:
    Not necessary, but should probably order loadouts so that they go from 1st - 4th (Currently 1-4-2-3)
    Deathshroud cannon has Skathach Wraithknight in name
    The two optional weapon loadouts currently aren't optional (selecting nothing gives a starcannon)

- [x] Irillyth:
    Spear of Starlight is an included asset instead of a trait asset - Gives error message

**Comment by UraharaKisuke88** [comment]
All issues besides Voidreavers and Voidscarred fixed by me in Aeldari/Drukhari common v10.2.12. Voidreavers and Voidscarred apparently fixed by Mundangerous, awaiting confirmation from @Nemo3823 before closing issue and calling QA complete for Aeldari

**Comment by Nemo3823** [comment]
All issues fixed
