### ISSUE TITLE
Agents of the Imperium QA issues

### ISSUE THREAD

**Issue by KevinFournier** [RosterizerTestData/Warhammer40k10e#125]
### Vindicare assassin

- [x] missing Invulnerable save 4+ ability.

### Culexus Assassin

- [x] missing Invulnerable save 4+ ability.
- [x] missing Soulless Horror ability
- [x] missing Abomination ability

### Inquisitor Greyfax

- [x] missing `ANTI-CHARACTER 4+`, `Dev wound` and `Precision` on Castigation weapon
- [x] missing `ANTI-PSYKER 2+`, `Dev wound`, precision`, on Condemnor stake
- [x] on condemnor stake, `Rapid fire 1` keyword is display as `Fire 1`

### Rogue Trader Entourage

- [x] Warrant of Trade: description is there twice. The first one is incomplete.
- [x] Specialist have the stat of the Rogue Traders
- [x] Specialist should all have one of the different  loadout and it should not be changeable

### Voidsmen-at-arms

- [x] one of the voidsmen should have `laspistol`, `voidsman rotor cannon` and `close combat weapon`
- [x] default voidman weapon’s wrong, they should have `lasgun`, `laspistol` and `close combat weapon`
- [x] The doggo is a good boy.

### Imperial navy breachers

- [x] Default loadout:
    - [x] All 8 navis (including sergeant) should have: `Navis shotgun` and `close combat weapon`
    - [x] One should have: `Navis heavy shotgun`, `close combat weapon` and `endurant shield`
    - [x] One should have: `Navis las-Volley` and `close combat weapon`

### subductor Squad

- [x] The cyber-mastiff has a save of 4 instead of 3+ and an OC of 2 instead of 1. (I don’t know if their is a sheet somewhere else with their dog stat)

### Exaction squad

- [x] The cyber-astiff has the same profil as the subductor one. So it have a OC of 2 instead of 1.
- [x] No error when equiping more than 2 special weapon in the squad
- [x] No error when equiping 2 time the same special weapon

**Comment by Nemo3823** [comment]
Fixed in 10.2.15 Imperium manifest!
