### ISSUE TITLE
Astra Militarum QA Issues - Core Indexes part 1

### ISSUE THREAD

**Issue by Enzarel** [RosterizerTestData/Warhammer40k10e#127]
General/Shared
- [x] All officers have the entire text of their Orders ability pasted inside the descriptions of their last non-generic ability. I've noted which abilities were affected in the issue lists for the individual units.

Stratagems:
- [x] Overwatch: only listed under the charge phase, should also be under movement phase.

General Wargear:
- [x] Hunter-killer missile: [One Shot] weapon ability lacks description; should be "The bearer can only shoot with this weapon once per battle."
- ~~Weapons with multiple profiles show up under "Weapon" instead of "Ranged Weapon".~~ _Intended behavior -Mund_

Regimental Preacher:
- [x] Wargear selection not set up right at all.

Lord Solar Leontus:
- [x] Collegiate Astrolex ability: duplicate Orders text at the end of the ability description.
- [x] Supreme Commander: not scripted properly (another model can be the warlord without provoking roster errors; no errors if Leontus isn't the warlord)

Ursula Creed
- [x] Tactical Genius ability: duplicate Orders text at the end of the ability description.

Cadian Castellan
- [x] Get Back in the Fight ability: duplicate Orders text at the end of the ability description.
- [x] Should be equipped with a Laspistol by default, has a Bolt pistol.
- [x] Boltgun should replace melee weapon, instead replaces pistol. No validation error on incompatible wargear choice.

Tank Commander
- [x] Death Befitting an Officer ability: duplicate Orders text at the end of the ability description.
- [x] Should be able to not take sponsons or pintle guns, and that should be the default option.
- [x] Executioner plasma cannon - supercharge should deal D6+3 attacks and 3 damage, currently only deals D3 attacks and 2 damage.
- [x] Exterminator autocannon's [Twin-Linked] ability: has an extra space, "Twin -linked"; doesn't have a description; should be listed after Sustained Hits 1, not before.
- [x] Punisher gatling cannon should have strength 5, currently has strength 6.
- [x] Recommend making turret weapons always show up on the top of the weapons list.

Platoon Command Squad
- [x] Orders: duplicate text at the end of the ability description.
- [x] Platoon Commander: Bolt pistol and Plasma pistol BS read "4*+", should read "4+".
- [x] Master-vox, Regimental Standard, Medi-pack, and all special weapons (Flamer, Plasma, etc.) should be limited to 1 per squad; currently no error if duplicates are taken.
- [x] Recommend splitting the default stack of 4 veterans into individual entities, to make equipment assignment easier.
- [x] Veteran Heavy Weapons Team: doesn't need a quantity counter. Recommend adding a "Unit Composition" dropdown to the unit, like in Infantry Squads.
- [x] Wargear abilities don't show up on the unit card if the relevant wargear is taken.

Cadian Command Squad
- [x] Regimental Standard wargear ability: duplicate Orders text at the end of the ability description.
- [x] Lacks "Orders" ability.
- [x] Lacks "Infantry", "Imperium", "Grenades", "Cadian" keywords.
- [x] Cadian Commander: keywords not set up properly, all placed in the base unit's keywords after a "CADIAN COMMANDER:" keyword. Recommend replicating the setup from the Platoon Command Squad and putting the keywords on the model itself.
- [x] Cadian Commander & Chainsword veteran: can't take bolt pistol. Plasma pistol BS should be 4+, currently is 3+.
- [x] Banner veteran: default wargear should be Lasgun + Banner, currently is Flamer.
- [x] All veterans (except the one with the chainsword) shouldn't have laspistols (or be able to replace them with plasma pistols), currently they do.
- [x] Regimental standard wargear ability doesn't go away if the wargear is replaced.

Iron Hand Straken
- [x] Been There, Seen It, Killed It ability: duplicate Orders text at the end of the ability description.

Primaris Psyker
- [x] Ability names: The "p" in "(psychic)" should be capitalised, as per original text.

Gaunt's Ghosts
- [x] Only Ibram Gaunt should have the Ivulnerable 5+ save, currently it's listed as a unit-wide ability.
- [x] Covert Stealth Team ability: duplicate Orders text at the end of the ability description.
- [x] Lacks "Orders" ability.
- [x] All Tanith Ghosts have Ibram Gaunt's stats; should have 5+ saves and 7+ leadership, currently have 4+ and 6+.
- [x] Unit keywords listed in reverse order of appearance.

Regimental Attachés
- [x] Lacks "Infantry", "Imperium", "Regimental Attaches" keywords. Keyword "ASTROPATH: Psyker" should be removed and set up on the model itself.
- [x] Divination (psychic): "p" should be capitalized.
- [x] Attachés ability: last sentence of description should be preceeded by a line break. Maybe do bullet points?

Ogryn Bodyguard
- [x] Typo in "Weapon/Shield", currently reads "Weapon/Sheild".
- [x] Default weapon should be a ripper gun, currently is a grenadier gauntlet.
- [x] Ripper gun lacks ranged profile. See also: Ogryn Squad
- [x] Should have "Loyal Protector" special ability containing attachment rules, similar to how Regimental Attachés do it.

Nork Deddog
- [x] Lacks "Huge Knife" melee weapon.
- [x] Should have "Loyal Protector" special ability, see above.

All battleline infantry (below)
- ~~Taking a Vox-caster doesn't add the relevant wargear ability to the unit.~~ _Keeping as is so the ability stays on the bearer --Mund_
- [ ] Recommend adding the Unit Composition dropdown (as seen on the Infantry Squad) to all the other units, for ease of choosing a unit size.
- [x] Error shows up about needing "1 sergeant per 9 guardsmen" if there's less than 9 guardsmen. Technically not a bad thing, just would be neater if it didn't.

Infantry Squad
- [x] Heavy Weapons Team: lacks laspistol and close combat weapon.
- [x] Sergeant: Bolt pistol and Plasma pistol BS read "4*+", should read "4+".

Cadian Shock Troops
- [x] Sergeant: Bolt pistol + Chainsword weapons option adds a Cadian Veteran Guardsman model to the Sergeant instead of a chainsword.

Death Korps of Krieg
- [x] Watchmaster: Boltgun, Boltpistol, and Plasma Pistol should have BS 4+, currently all have 3+.
- [x] No error if any combination of Vox/Vox+Plasma/Plasma is taken in excess of the allowed number.
- [x] No error if more than 2 different special weapons (from the first bullet point) per 10 models are taken.

Catachan Jungle Fighters
- [x] Jungle Fighter troop: shouldn't have laspistols, currently they do.
- [x] No error if too many Vox-casters are taken.

Kasrkin
- [x] Vox caster & Melta Mine abilities: not properly hidden if the unit doesn't contain the required wargear; shown by default.
- [x] Kasrkin Sergeant: shouldn't be able to take a Close combat weapon, currently can by replacing the chainsword.
- [x] Kasrkin Sergeant: Plasma Pistol should have BS 4+, currently has 3+.
- [x] Kasrkin Troopers: plural form name, should be changed to singular.
- [x] Kasrkin Trooper: no Laspistol + Melta Mine weapon option.
- [x] No error if more than 1 marksman rifles is taken.
- [x] No error if more than 4 special weapons (from the first bullet point) are taken.
- [x] Special weapons are limited to "2 in 10", should be 2 per unit no matter the size.

Sergeant Harker
- [x] Payback Time ability: duplicate Orders text at the end of the ability description.

Munitorum Servitors
- [x] All servitors are equipped with close combat weapons, they shouldn't be. (but expect GW to FAQ it back by the end of the month)
- [x] No error if more than 2 different heavy weapons are taken.
- [x] No error if more than 2 of the same heavy weapon is taken, either.
- [x] Plural form model name

Commissar
- [x] Political Overwatch ability: duplicate Orders text at the end of the ability description.

Ogryn Squad
- [x] Ripper gun should have a multi-profile container set up. See also: Ogryn Bodyguard
- [x] Ogryns: plural form name

Bullgryn Squad
- [x] Typo in the shield selection dropdown: "Brute Sheild"
- [x] Bullgryns: plural form name

Ratling Snipers
- [x] Models should have the singular form of the name.
- [x] No need for a quantity counter or the ability to add models; the size of the unit is set, and there are no wargear options.

Atillan Rough Riders
- [x] Rough Rider Sergeant: lacks a lasgun, laspistol, and steed's hooves.
- [x] Rough Rider Sergeant: the tickbox to add a Power sabre is titled "Power Sword".
- [x] Rough Riders: plural form name.
- [x] The sergeant is not counted for or restricted by the goad lance limit of 1 per 5 models.

Listed in order of index appearance/priority. Scout Sentinel and below to follow. Forge World indices when pigs fly.

=][= A single thought of heresy can blight a lifetime of faithful duty. =][=

**Comment by Mundangerous** [comment]
Guard 10.2.3 and 10.2.4 contain these fixes

**Comment by Mundangerous** [comment]
Only open item is the unit comp dropdown. We only did that for Infantry Squad because of the mess with HWTs. I think given the variety of loadout mixes within the unit compositions, it's probably better to just leave them, but I could be convinced.

**Comment by Nemo3823** [comment]
Personally, I agree that it doesn't need to be added. I'm cleaning up issues so feel free to reopen this if you want to think about it more.
