### ISSUE TITLE
Astra Militarum QA Issues - Core Indexes part 2

### ISSUE THREAD

**Issue by Enzarel** [RosterizerTestData/Warhammer40k10e#129]
High Priority:
- Shadowsword doesn't have its Volcano cannon
- Additional missing guns on the Rogal Dorn, HWS, Banehammer, Stormlord, and Shadosword

Scout Sentinels
- [x] Plural form name
- [x] Default ranged weapon should be multi-laser, currently is autocannon.

Armoured Sentinels
- [x] Plural form name
- [x] Default ranged weapon should be multi-laser, currently is autocannon.

Hellhound
- [x] Default turret weapon should be inferno cannon, currently is chem-cannon.

Rogal Dorn Battle Tank
- [x] Lacks a heavy stubber (single, default, non-replacable).
- [x] Lacks the armoured tracks melee weapon.
- [x] Hull Weapon dropdown: includes every single weapon on the card as a possible choice, should only include the Castigator and Oppressor cannons. _Fixed with Castigator and Pulveriser, per datasheet --Mund_
- [x] Sponson weapons dropdown: choosing "-" equips two Multi-meltas instead of nothing.
- [x] Turret Weapon dropdown: Oppressor cannon doesn't come with a co-axial autocannon.
- [x] Could rename the "Hull Weapon" dropdown to "Hull Cannon"?

Heavy Weapons Squad
- [x] Should have OC 2, currently have 4.
- [x] Lack las small arms and Weapons team close combat weapons.
- Could split the stack into 3 individual models? _Leaving as is, pretty common to run three of a kind --Mund_

Field Ordnance Battery
- [x] Default weapon should be malleus rocket launcher, currently is bombast field gun.
- [x] Ranged Weapon dropdown: includes every weapon in the unit, should only include rocket launcher, field gun, and lascannon.
- Could split the stack, as above? _As above --Mund_

All Leman Russ variants
- [x] Only the Exterminator has its weapon dropdowns in the proper, original index-card order, and stands out from the rest as a result.

Leman Russ Battle Tank
- [x] 2 Multi-meltas sponson weapon equips Heavy flamers instead.
- [x] Should have option to not take pintle and sponson guns, and that option should be default.

Leman Russ Demolisher
- [x] Pintle Weapon dropdown: choosing "-" equips a Storm bolter instead of nothing.
- [x] Pintle Weapon dropdown: "-" should be the default.
- [x] Sponson Weapons dropdown: lacks "-" option, which should be the default.

Leman Russ Vanquisher
- [x] 2 Multi-meltas sponson weapon equips Heavy flamers instead.
- [x] Should have option to not take sponson guns, and that option should be default.

Leman Russ Punisher
- [x] 2 Multi-meltas sponson weapon equips Heavy flamers instead.
- [x] Should have option to not take sponson guns, and that option should be default.

Leman Russ Executioner
- [x] Should have option to not take sponson guns, and that option should be default.

Leman Russ Exterminator
- [x] Exterminator autocannon: typo, extra space in "Twin -linked" weapon ability. Broken description as a result.
- [x] Should have option to not take pintle and sponson guns, and that option should be default.

Leman Russ Eradicator
- [x] 2 Multi-meltas sponson weapon equips Heavy flamers instead.
- [x] Should have option to not take sponson guns, and that option should be default.

Manticore
- [x] Lacks armoured tracks melee weapon.

Wyvern
- [x] Wyvern quad stormshard mortar: Stats have been shifted one space to the right; giving it range 2d6, 4+ attacks, and S0, amongst others.

Valkyrie
- [x] Default front weapon should be a multi-laser, currently is lascannon.
- [x] Umm technically it's a *Nose* Weapon :nerd:

Aegis Defence Line
- [x] Lacks abilities
- [x] Keywords: "Aegis Defence Line" should be last, is first.
- [ ] Is in the vehicle category, despite not being a vehicle. Recommend renaming category to "Vehicle/Fortification"

All Baneblade variants
- [x] Damaged ability: lacks "subtract 4 from its Objective Control characteristic" part.
- [x] Deadly Demise ability: should be D6+2, currently is D6. Pretty sure value is entered separately for each unit; noted on each.

Baneblade
- [x] Deadly Demise ability: should be D6+2, currently is D6.
- [x] Second sponson set only adds one lascannon.
- [x] Second sponson set should be off by default.

Banehammer
- [x] Deadly Demise ability: should be D6+2, currently is D6.
- [x] Second sponson set only adds one lascannon.
- [x] Lacks (hull-mounted) twin heavy bolter.
- [x] Firing Deck ability: should be 12, is 1.
- [x] Lacks Transport ability (capacity 26 btw).

Banesword
- [x] Deadly Demise ability: should be D6+2, currently is D6.
- [x] Second sponson set doesn't add any lascannons, names lack "+ 2 Lascannons".
- [x] Lacks an option to not take the second sponson set, which should be default.

Doomhammer
- [x] Deadly Demise ability: should be D6+2, currently is D6.
- [x] Second sponson set only adds one lascannon.
- [x] Lacks an option to not take the second sponson set, which should be default.
- [x] Firing Deck ability: should be 12, is 1.

Hellhammer
- [x] Deadly Demise ability: should be D6+2, currently is D6.
- [x] Second sponson set doesn't add any lascannons, names lack "+ 2 Lascannons".
- [x] Lacks an option to not take the second sponson set, which should be default.

Shadowsword
- [x] Deadly Demise ability: should be D6+2, currently is D6.
- [x] No main gun!!!!
- [x] Second sponson set: "-" option doesn't properly remove the second sponson set.
- [x] Second sponson set only adds one lascannon.
- [x] Lacks (hull-mounted) twin heavy bolter.

Stormlord
- [x] Deadly Demise ability: should be D6+2, currently is D6.
- [x] Second sponson set only adds one lascannon.
- [x] Firing Deck ability: should be 24, is 2.
- [x] Lacks (hull-mounted) twin heavy bolter.
- [x] Lacks 2 heavy stubbers.
- Has melee weapons listed after ranged weapons, unlike every other unit so far. _Can't easily control, deprioritizing --Mund_

Stormsword
- [x] Deadly Demise ability: should be D6+2, currently is D6.
- [x] Second sponson set: "-" option doesn't properly remove the second sponson set.
- [x] Second sponson set only adds one lascannon.

Militarum Tempestus Command Squad
- [x] Leader ability: doesn't include which units this unit can lead (Tempestus Scions).
- [x] Tempestor Prime ability: doesn't include the actual ability (the one in the front of the card), only the special ability from the back with the same name.
- [x] Lacks Orders ability.
- [x] Master vox + pistol: should remove (replace) the bearer's hot-shot lasgun, currently doesn't.
- [x] Special weapons: should be limited to 1 per unit.

Tempestus Scions
- [x] Shouldn't have "Leader" ability.
- [x] Vox-caster: should be limited to 1 per unit.

Taurox Prime
- [x] Hull Weapon: default should be twin volley gun, currently is twin autocannon.

Forgeworld stuff might or might not necessarily require light-to-detailed QAing.

≡][≡ What is the terror of death? That we die our work incomplete. ≡][≡

**Comment by Mundangerous** [comment]
These are all in Guard 10.2.5.

Only open item is the class of Aegis Defense Line. @TheGameKnave what's the effort to rename the Vehicle class? Does that risk blowing other stuff up? This affects several factions (anyone with fortifications and enough units to split infantry and vehicles).

**Comment by Nemo3823** [comment]
I'll ping him in discord about it, but considering none of the fortifications in any of the other manifests have their own category, this isn't a guard issue.
