### ISSUE TITLE
Tyranids - Invasion Fleet - Synaptic Linchpin Inconsistencies

### ISSUE THREAD

**Issue by MLPaladin888** [RosterizerTestData/Warhammer40k10e#142]
1. Synaptic Linchpin is supposed to cost 20 points, but it currently shows up as 10 points in the manifest.
2. The spelling in the manifest shows up as "Synaptic Lynchpin" rather than how it shows up as "Synaptic Linchpin" elsewhere (such as the MFM)

**Comment by OldManBayaz** [comment]
Thank you!
Will be fixed in 10.6.2, should be out in a hour or less.
