### ISSUE TITLE
Astra Militarum - Infantry Squad - Heavy Weapons Team - Data Issue

### ISSUE THREAD

**Issue by MLPaladin888** [RosterizerTestData/Warhammer40k10e#143]
The Heavy Weapons Team's pistol is listed as a "Las small arms".  It is called a "Laspistol" in the index.
The Heavy Weapons Team's pistol is listed as having a range of 18".  It has a range of 12" in the index.

**Comment by TheGameKnave** [comment]
Fixed in 10.5.11
