### ISSUE TITLE
Death Guard Cultist Champion should not have wargear options

### ISSUE THREAD

**Issue by MLPaladin888** [RosterizerTestData/Warhammer40k10e#146]
The Death Guard Cultist Champion model within the Death Guard Cultist unit should only have the default loadout.  The options should only apply to the "regular" Death Guard Cultist models.

For every 10 models in the unit, 1 Death Guard Cultist’s Cultist firearm can be replaced with 1 flamer.
For every 10 models in the unit, 1 Death Guard Cultist’s Cultist firearm can be replaced with 1 heavy stubber.
For every 10 models in the unit, 1 Death Guard Cultist’s Cultist firearm can be replaced with 1 grenade launcher.

Currently the champion's loadout dropdown incorrectly populates with the 2 default weapons (both its melee and ranged) as well as the 3 special weapon options.

**Comment by OldManBayaz** [comment]
Fixed on 7.1
