### ISSUE TITLE
Tempestor Prime Ability in the Militarum Tempestus Command Squad incorrect

### ISSUE THREAD

**Issue by MLPaladin888** [RosterizerTestData/Warhammer40k10e#147]
Currently says: "If this unit’s Tempestor Prime model is your Warlord, Tempestus Scions units from your army have the Battleline keyword."

Should say: "While this unit contains a Tempestor Prime, ranged weapons equipped by models in this unit have the [Susutained Hits 1] ability."

**Comment by OldManBayaz** [comment]
https://i.imgur.com/62obnOz.jpeg

This one is mostly an issue with GW naming two different effects with same name. Both are represented on Rosterizer.
![Captura de tela 2024-01-25 021457](https://github.com/RosterizerTestData/Warhammer40k10e/assets/99839046/8f887f37-f863-44bc-b3a6-0b3bfbc24ddd)


Maybe we could place those in a different location to reduce confusion.
