### ISSUE TITLE
Sisters: Battle Sisters Squad wargear issues

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#16]
- No error is raised if they all have special/heavy weapons
- They all have storm bolters by default
- The unit has a Simulacrum Imperialis even if no model does

**Comment by Nemo3823** [comment]
Fixed

**Comment by ThePants999** [comment]
Fixed by f02a0dcf4a3731af7ee0b6ed8cc96d122b4f5239
