### ISSUE TITLE
Missing duplicate versions of several Legends units

### ISSUE THREAD

**Issue by OldManBayaz** [RosterizerTestData/Warhammer40k10e#166]
Some units from Space Marines and Chaos Space Marines Legends can be used in other factions with some keyword changes. These are currently not implemented in Rosterizer. A list of these units and source documentation follows:

- **Horus Heresy Legends: Adeptus Astartes.**
Units here need to go from the Space marine rulebook to Thousand Sons, Chaos Space Marines, Death Guard and World Eaters rulebook.

[Horus Heresy Legends: Adeptus Astartes PDF](https://assets.warhammer-community.com/warhammer40000_legends_heresyadeptusastartes_eng_24.09-rdmyjwqk0k.pdf)
![Horus Heresy Astartes](https://github.com/user-attachments/assets/9f15a8f6-d504-4023-b528-da06179d11c5)

- **Legendary Units**
Units here go from the Chaos Space Marine rulebook to the Death Guard, Thousand Sons and World Eaters rulebooks.

[Legendary Units PDF](https://assets.warhammer-community.com/warhammer40000_legends_legendaryunits_eng_24.09-0uefelwovp.pdf)
![Legendary Units](https://github.com/user-attachments/assets/0b45ebdc-3b58-410f-b6ba-8b264c4833b0)

- **Horus Heresy Legends: Heretic Astartes.**
Units here go from the Chaos Space Marine rulebook to the Death Guard, Thousand Sons and World Eaters rulebooks.

[Horus Heresy Legends: Heretic Astartes PDF](https://assets.warhammer-community.com/warhammer40000_legends_heresyhereticastartes_eng_24.09.13-c2r9i7kq08.pdf)
![Horus Heresy Heretic Astartes](https://github.com/user-attachments/assets/aaef7cb5-e7f7-431f-9617-f68d3471419b)

**Comment by TheGameKnave** [comment]
These are now moved to chaos in order to allow them to be used by any faction, but will need some kind of ruling in order to adjust the keywording and traits.
