### ISSUE TITLE
Adeptus Custodes - Shield Captain

### ISSUE THREAD

**Issue by mr-frog** [RosterizerTestData/Warhammer40k10e#18]
When adding a variety of different Shield Captains to a roster (I have not tried every single combination), the regular shield-captain shows up as having to many units of this type in the army. This seems like a bug to me
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/55178725/a6082f0d-849a-44f4-a419-c59218950c59)

**Comment by ThePants999** [comment]
Issue here is that anyone with the Shield-Captain _keyword_ is contributing to the count. A generic fix is in the works but is too far away so I'll need to implement a specific fix for this use case - and @TheGameKnave note that the "Captain" datasheet in SM is going to hit the same problem.

**Comment by TheGameKnave** [comment]
> Issue here is that anyone with the Shield-Captain _keyword_ is contributing to the count. A generic fix is in the works but is too far away so I'll need to implement a specific fix for this use case - and @TheGameKnave note that the "Captain" datasheet in SM is going to hit the same problem.

The fix I outlined works well, but I was right; having rule name collisions with removed rules causes problems, so I just omitted the period in the new rule.
<img width="213" alt="image" src="https://github.com/RosterizerTestData/Warhammer40k10e/assets/575686/cfdd771b-973c-43d5-b1ee-cbb235dc8931">

<img width="400" alt="image" src="https://github.com/RosterizerTestData/Warhammer40k10e/assets/575686/abbb2a6e-ee5f-4ae6-93db-441979149e81">
