### ISSUE TITLE
Adeptus Custodes - Shield Captain on Jetbike

### ISSUE THREAD

**Issue by mr-frog** [RosterizerTestData/Warhammer40k10e#19]
The Shield-Captain on Dawneagle Jetbikes raises an Error in the text-profile about the wargear requiring custom work
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/55178725/fc41d2b3-4576-4c60-b699-84bc5e2dd0c5)

**Comment by ThePants999** [comment]
Fix with me to publish

**Comment by ThePants999** [comment]
Fixed by 01504a351083985f1696f40997a5b001fe92179d
