### ISSUE TITLE
Imperial Knights - Canis Rex: Sir Hekthur is missing his Stats

### ISSUE THREAD

**Issue by mr-frog** [RosterizerTestData/Warhammer40k10e#21]
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/55178725/977f4730-a391-4ce5-9cd5-9580ed638b84)
Sir Hekthur has no Stats (eg. Wounds / T)

**Comment by ThePants999** [comment]
Fixed by bd77e7c6e0683ff870b2cf43bbcd1d3bc79088db
