### ISSUE TITLE
Imperial Knights - Canis Rex - Weapons listed as Wargear

### ISSUE THREAD

**Issue by mr-frog** [RosterizerTestData/Warhammer40k10e#22]
Canis Rex Weapons are listed as Wargear in Rosterizer
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/55178725/73ad7ba1-827f-435e-9a1a-d5b887cb075f)

this makes yellowscribe break
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/55178725/a653f6b1-1f3a-420f-a18c-2d974ab46765)

**Comment by ThePants999** [comment]
"Wargear" is deliberate - it's used for any weapon with multiple profiles - but it's a shame that distinction gets exposed to the user.

Yellowscribe is designed to understand that, and successfully copes with it in many other cases, I'll have to dig to see what's going on there.

**Comment by TheGameKnave** [comment]
@ThePants999 i think the solution is to just change the class to "weapon"... The reason I used wargear is because, back when I started 9e, I thought it would be weird to let weapons contain other weapons, but it should actually be just fine, and would be more semantic.
Probably want to do a search for any rules that might care about wargear really before doing a search/replace.

**Comment by ThePants999** [comment]
@TheGameKnave I _would_ love that idea, except for these guys:

![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/2923823/38f24bbb-c6fe-4b14-b497-2bf88008d315)
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/2923823/e6a1313b-c57b-4e5d-b286-b4f5c2d6d152)

One weapon with a ranged profile and a melee profile. (I suppose that we could add a "Mixed Weapon" class for them?)

**Comment by ThePants999** [comment]
Hilariously, I've spent hours developing a script to overhaul all the manifests to fix this issue everywhere, and have fixed countless instances of it...

...except this one. For some reason, Canis Rex's weapons weren't tagged "Multi-weapon" so my script didn't handle them. Sigh.

**Comment by ThePants999** [comment]
Fixed by bd77e7c6e0683ff870b2cf43bbcd1d3bc79088db
