### ISSUE TITLE
World Eaters Quick QA pass issues

### ISSUE THREAD

**Issue by hunterprime** [RosterizerTestData/Warhammer40k10e#23]
Just did a very brief QA pass on WE for a a game I am about to play. [](https://rosterizer.com/roster/HiveBreachedExpert)

- Jakhals model count of 8 is locked which prevents you from spliting one off to equip Mauler chain blades. 
- Jakhals Icon of Khorne says you have too many equipped after selected one
- Jakhals can equip the entire block of 8 Jakhals with Mauler chainblades and not get a validation error

- Rhino Havok launcher is referencing the TSon one **Thousand Sons Rhino—Havoc launcher**

- Eightbound are not displaying wargear in the text view. Below is the sample output

   Model
  └ Eightbound Champion
   Model
  └ 2x Eightbound

**Comment by ComanderChaCha** [comment]
Fixed in version 1.2.2
