### ISSUE TITLE
Evaluating tally == 0 returns False if nothing is contributing to the tally

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#27]
If you have a rule evaluating {roster}->tally->something == 0, and there are no "something"s in the roster, the eval's integer result is correctly 0 but its truthy result is incorrectly False. This is a Rosterizer bug.

I've had to work around this by adding tracking stats at the roster scope initialised to 0, e.g. Armigers in the Imperium manifest, and these should be reverted to tallies once the bug is fixed.

**Comment by TheGameKnave** [comment]
@ThePants999 Our official recommended workaround is "not min 1" for most cases of trying to evaluate the presence of a missing tally/track (will make it easier to fix globally when the defect is fixed)

**Comment by TheGameKnave** [comment]
closing, as this is captured in the app defect tracker and isn't really data-related
