### ISSUE TITLE
Space Marines: Capt in Term Armour storm bolter should be Rapid Fire 2

### ISSUE THREAD

**Issue by Mundangerous** [RosterizerTestData/Warhammer40k10e#47]

**Comment by TheGameKnave** [comment]
This is the case. It might have been related to the bug that was solved in Jun28's nightly.
<img width="220" alt="image" src="https://github.com/RosterizerTestData/Warhammer40k10e/assets/575686/739ce98a-824b-479e-8cab-3d5b965c7d68">
