### ISSUE TITLE
Space Marines: Capt in Term Armour combi-weapon should be Anti-Infantry 4+ and Rapid Fire 1

### ISSUE THREAD

**Issue by Mundangerous** [RosterizerTestData/Warhammer40k10e#48]

**Comment by TheGameKnave** [comment]
This appears to be the case. Perhaps it was fixed in another commit?
<img width="219" alt="image" src="https://github.com/RosterizerTestData/Warhammer40k10e/assets/575686/c749029e-0b37-40e7-a52d-2a26e138db23">
