### ISSUE TITLE
Per-model keywords not handled

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#6]
A Keywords section like this:

![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/2923823/2881da67-965f-4cb0-b67b-4069808bb1d8)

has been parsed simply:

![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/2923823/288a0b8d-caee-44c3-9fd4-8664c0697276)

and our parser is handling that equally simply. WIBNI we parsed that properly and assigned the right keywords to the right models. However, this scenario is probably rare enough to fix manually.

**Comment by TheGameKnave** [comment]
Needs to be handled manually on a case-by-case, as it's infrequent enough to not warrant coding for.
