### ISSUE TITLE
Space Marines: Guilliman's Primarch abilities not correctly modelled

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#60]
The Author of the Codex abilities should be children of Author of the Codex.

**Comment by TheGameKnave** [comment]
Isn't that the case?
<img width="740" alt="image" src="https://github.com/RosterizerTestData/Warhammer40k10e/assets/575686/ae8f2d87-a0d5-46ea-b569-c298aebcc2b9">

**Comment by TheGameKnave** [comment]
Fixed
