### ISSUE TITLE
Space Marines: Intercessor and Eliminator sergeants don't have full wargear options

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#68]
Report from Astro Ambulance: "intercessor sgt can only equip one weapon, eg bolt rifle OR grenade launcher OR power fist, instead of having a melee weapon, a pistol, and a bolt rifle OR hand flamer OR plasma pistol. similar issue with the eliminator sgt"

**Comment by TheGameKnave** [comment]
fixed in 10.2.4
