### ISSUE TITLE
Adepta Sororitas' Canoness model rod of office selection problem

### ISSUE THREAD

**Issue by TheGameKnave** [RosterizerTestData/Warhammer40k10e#70]
Adepta Sororitas' Canoness model. In the Index, it states that if she's equipped with a plasma pistol and power weapon, then she can be equipped with a rod of office, but in Rosterizer, the rod of office can only be selected when she is equipped with a chainsword and plasma pistol.

**Comment by Nemo3823** [comment]
Fixed in 10.2.11
