### ISSUE TITLE
Tally double-counts if another asset has the same name as a unit

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#8]
In the Daemons index there's a unit called "Bloodmaster" who has an ability called "Bloodmaster". Unfortunately, the tallying logic is apparently just based on designation and not the combo of designation+classification, so after adding two of these units to a roster, I've got a roster-scope tally that includes "Bloodmaster": 4, and now the "Too many of this unit type in the army" rule is triggering 🙂

**Comment by TheGameKnave** [comment]
This needs a little more investigation to figure out the best fix. If abilities never otherwise need to be tallied, we can put a global rule on the ability class to set its own designation tally to 0. This could actually be targeted, so it only does so if its designation matches its parent's.

**Comment by TheGameKnave** [comment]
Fixed in 10.0.10
