### ISSUE TITLE
Tau Breacher Team - Guardian drone only available in drone slot 1

### ISSUE THREAD

**Issue by frenchy13** [RosterizerTestData/Warhammer40k10e#84]
When choosing drones for the tau breacher team (via the Breacher Fire Warrio Shas'ui) the Guardian Drone is only available in the 1st Drone slot and not the second (even if not selected in the first slot).

**Comment by Listerisonfire** [comment]
Hello,

Thanks for bringing this to my attention however the breacher squad can only have 1 guardian drone in its squad so thats why i only put it drone slot 1.
